### ISSUE TITLE
Juggernaut Rework [3 skills + 6 talents]

### ISSUE THREAD

**Issue by X-TheDark** [Shushishtok/dota_imba#533]
Bladefury:
1) Remove evasion bonus while spinning.
2) While spinning, Juggernaut deflects ranged attack projectiles aimed at him, taking no damage from them and firing that projectile towards a random enemy in 800 range.

Blade Dance:
1) Blade Dance's active changes from Unit target to Point target. Whenever it is ready, it plays a sound indicating it is ready to be used. (Rosa's lightsaber sound clip)
2) Reaching 3 Secret Blade stacks allows using Blade Dance's active, consuming all Secret Blade stacks. Causes Juggernaut to slash each enemy in his path once. When the dash ends, enemies hit are slashed again in the same order they were hit until all Secret Blade stacks are used, up to 3 slashes per enemy. Has a 3 seconds cooldown.
3) Attacking an enemy grants Juggernaut a stack of Secret Blade for 3.5 seconds. This can refresh and stack with itself infinitely. This buff would have Slice and Dice's icon.
4) Critting an enemy grants Juggernaut with Wind Dance normally, which grants bonus agility. (no changes)

Omnislash:
1) Add a varied amount of damage so Omnislash would always have 225 damage at the minimum. If the bonus damage grants more than the minimum threshold, no damage is added. (100 damage becomes 225, 180 damage becomes 225, 250 damage stays 250, etc.)
2) Omnislash Cooldown reduction per slash removed.
3) Static +80 bonus damage changed to 35% of Juggernaut's agility.

-------------------
TALENTS:
Remove:
+1% heal
+5% crit
+170 bladefury dps
+40% evasion
-2 Blade Dance CD
-3 Bladefury CD.

Apply:
1. Blade Fury slowly increases in size.
2. Blade Fury acts as a vaccum, sucking units towards Juggernaut.
3. Blade Dance's active strikes three times: once in a straight line forward, and twice to the sides. Can hit the same enemy multiple times per dash.
4. Healing Ward also increases the attack speed of units in its range by 50/100 (moving/fortified).
5. Landing a Blade Dance critical grants you stacks, similar to Wind Dances. Stack timers are independent and last 12 seconds. Each stack grants 1% agility increase to Omnislash bonus damage (which is 35% base).
6. Omnislash sends an image of Juggernaut to commit the slashes: Juggernaut is free to continue as normal.

**Comment by Shushishtok** [comment]
Done!
