### ISSUE TITLE
Silencer Rework [3 skills + 5 talents]

### ISSUE THREAD

**Issue by X-TheDark** [Shushishtok/dota_imba#616]
Glaives of Wisdom:
1) Remove Brain Drain. (mana burn on attack)
2) New Scepter effect: grants 100% bonus damage on silenced targets and causes Silencer's Glaives to pierce spell immunity. (parity with vanilla)

Global Silence:
1) Remove Arcane Curse on Global Silence.
2) Global Silence reworked: Global Silence applies a debuff on all enemies, but does not silence them. If an enemy attemps to cast a spell, it is interrupted immediately, and has Last Word applied on it. The target then is immediately silenced normally for the rest of the duration. Units that are channelling a spell are considered casting and are immediately treated as though they have cast a spell.
3) Ultimate cooldown same as vanilla.

Arcane Supermacy: Dying under Global Silence's effect only steals 1 intelligence. (instead of 2) (unless eligible for the full amount normally).

------------------------

TALENTS:
Remove:
+2 Arcane Curse duration
+2 Arcane Supermacy int steal
+25% Glaives int to damage.
+0.25s Glaives silence duration.
+20% Arcane Curse slow.

Apply:
1. Global Silence is unpurgable. If the target becomes magic immune, the effect stops, and the duration is paused until immunity wears off.
2. Arcane Curse spreads to nearby enemies in 900 AoE if the cursed target dies.
3. Silences caused by Silencer last 25% longer.
4. Glaives of Wisdom on targets afflicted with Global Silence causes the duration of the debuff to increase by 0.2 seconds.
5. Overrides Glaives of Wisdom's Debate Me. Each attack with Glaives of Wisdom that hits an enemy hero, it gains intelligence, up to 50% of their base intelligence. When this threshold is reached, the target's mind explodes, reducing intelligence to 0 for 3 seconds and dealing all reduced intelligence as pure damage. Does nothing while the target is debuffed with the Mind Explosion modifier.

**Comment by Shushishtok** [comment]
Done gracefully by zimber!
