### ISSUE TITLE
Wraith King Rework [2 skills + 4 talents]

### ISSUE THREAD

**Issue by X-TheDark** [Shushishtok/dota_imba#628]
Kingdom Come:
1) If Wraith King dies while broken, Kingdom Come does not proc.
2) Wraiths now grant 75g bounty when killed.

Scepter:
1) When a Wraith Formed hero accumulates damage equal to 15% of his max health, the buff duration decreases by one second, causing it to die if no time was remaining.
2) Scepter effect no longer has a limit to how many Wraiths can be active at once.

Soul Strike:
1) Wraiths Soul Strikes now deal magical damage instead of pure.
2) Wraith's Soul Strike's max health as damage from 9% to 14%.

------------------------------

TALENTS:
Remove:
+5% Mortal Strike crit chance
+2s Wraithfire Blast's duration
+15% lifesteal aura
+20% crit damage-to-health conversion

Apply:
1. Kingdom Come can now be cast normally to apply its effects without dying. Kingdom Come has 100 seconds cooldown, but can still proc normally if Wraith King dies. Has 1 second cast point.
2. Whenever an ally in Vampiric Aura's range takes damage, Wraith King is healed for 10% of the damage. This effect does not occur if Wraith King himself takes damage.
3. When the main target is hit by Wraithfire Blast, it burns brightly, dealing 80 damage per second to nearby units in 600 AoE. Each unit affected by Wraithfire Blast's debuff that is in range of the burn increases its damage by 40 for that tick. Lasts 4 seconds.
4. Reincarnation can now be set to auto cast. When it is toggled on, Wraith King emits a Reincarnation Aura, which reincarnates an allied hero in 900 AoE that dies in its vicinity. Triggers the cooldown normally when the effect occurs.

**Comment by Shushishtok** [comment]
Done by Mouji!
